# Generated by Django 3.1.7 on 2021-09-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hover_icon_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
