# Generated by Django 3.1.7 on 2021-10-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsSlidersImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='products_sliders_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.DeleteModel(
            name='ProductsSlidersImages',
        ),
    ]
