# Generated by Django 3.1.7 on 2021-10-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211002_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hover_icon_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
