# Generated by Django 3.1.7 on 2021-10-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_hover_icon_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hover_icon_title',
        ),
    ]
