# Generated by Django 3.1.7 on 2021-10-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_hover_icon_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=models.TextField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='ProductsSlidersImage',
        ),
    ]
